# Generated by Django 5.2.12 on 2026-03-25 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bnbuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='nothing yet'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(default='Moscow', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_night',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='rooms_count',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
