# Generated by Django 5.2.12 on 2026-03-25 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing_description_listing_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
