# Generated by Django 5.2.12 on 2026-03-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_listing_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
