# Generated by Django 5.2.12 on 2026-04-02 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_listing_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Вариант 1'), ('confirmed', 'Вариант 2'), ('canceled', 'Вариант 3')], default='pending')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
