# Generated by Django 5.2.12 on 2026-04-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_is_booked_alter_booking_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_booked',
        ),
    ]
