# Generated by Django 5.2.12 on 2026-04-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_booking_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_booked',
        ),
        migrations.AlterField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='main.listing'),
        ),
    ]
